// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/safedrive/Alerts.tsx": () => import("../components/mockups/safedrive/Alerts.tsx"),
  "./components/mockups/safedrive/Cameras.tsx": () => import("../components/mockups/safedrive/Cameras.tsx"),
  "./components/mockups/safedrive/Dashboard.tsx": () => import("../components/mockups/safedrive/Dashboard.tsx"),
  "./components/mockups/safedrive/GPS.tsx": () => import("../components/mockups/safedrive/GPS.tsx"),
  "./components/mockups/safedrive/Landing.tsx": () => import("../components/mockups/safedrive/Landing.tsx"),
  "./components/mockups/safedrive/Login.tsx": () => import("../components/mockups/safedrive/Login.tsx"),
  "./components/mockups/safedrive/Profile.tsx": () => import("../components/mockups/safedrive/Profile.tsx"),
  "./components/mockups/safedrive/Security.tsx": () => import("../components/mockups/safedrive/Security.tsx")
};
